application: game-911
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:       # static then dynamic

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /partials
  static_dir: static/partials

- url: /
  static_files: templates/index.html
  upload: templates/index\.html
  secure: always

- url: /_ah/spi/.*
  script: api.api

- url: /crons/send_reminder
  script: main.app


libraries:

- name: webapp2
  version: latest

- name: endpoints
  version: latest

